name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - mygento

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'oracle'
    # - name: Set up Flutter
    #   uses: subosito/flutter-action@v2
    #   with:
    #     channel: any
    #     flutter-version-file: pubspec.yaml
    - name: Clone Flutter SDK
      # We can't do a depth-1 clone, because we need the most recent tag
      # so that Flutter knows its version and sees the constraint in our
      # pubspec is satisfied.  It's uncommon for flutter/flutter to go
      # more than 100 commits between tags.  Fetch 1000 for good measure.
      run: |
        git clone --depth=1000 -b main https://github.com/flutter/flutter ~/flutter
        TZ=UTC git --git-dir ~/flutter/.git log -1 --format='%h | %ci | %s' --date=iso8601-local
        echo ~/flutter/bin >> "$GITHUB_PATH"

        # The Flutter tool assumes the tip of tree is "origin/master"
        # (or "upstream/master"):
        #   https://github.com/flutter/flutter/issues/160626
        # TODO(upstream): make workaround unneeded
        git --git-dir ~/flutter/.git update-ref refs/remotes/origin/master origin/main
    - run: flutter --version
    - name: Download Flutter SDK artifacts (flutter precache)
      run: flutter precache --universal
    - name: Download our dependencies (flutter pub get)
      run: flutter pub get
    - name: Build APK
      run: flutter build apk --release
  mac:
    runs-on: macos-15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: any
      #     flutter-version-file: pubspec.yaml
      - name: Clone Flutter SDK
        # We can't do a depth-1 clone, because we need the most recent tag
        # so that Flutter knows its version and sees the constraint in our
        # pubspec is satisfied.  It's uncommon for flutter/flutter to go
        # more than 100 commits between tags.  Fetch 1000 for good measure.
        run: |
          git clone --depth=1000 -b main https://github.com/flutter/flutter ~/flutter
          TZ=UTC git --git-dir ~/flutter/.git log -1 --format='%h | %ci | %s' --date=iso8601-local
          echo ~/flutter/bin >> "$GITHUB_PATH"

          # The Flutter tool assumes the tip of tree is "origin/master"
          # (or "upstream/master"):
          #   https://github.com/flutter/flutter/issues/160626
          # TODO(upstream): make workaround unneeded
          git --git-dir ~/flutter/.git update-ref refs/remotes/origin/master origin/main
      - name: Download Flutter SDK artifacts (flutter precache)
        run: flutter precache --universal
      - name: Download our dependencies (flutter pub get)
        run: flutter pub get
      - name: Build IPA
        run: flutter build ipa --no-codesign