name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - mygento

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'oracle'
    - name: Clone Flutter SDK (full)
      run: |
        git clone https://github.com/flutter/flutter.git ~/flutter
        echo ~/flutter/bin >> "$GITHUB_PATH"
        # Flutter expects origin/master to exist, even on main branch
        git --git-dir ~/flutter/.git update-ref refs/remotes/origin/master origin/main
    - run: flutter --version
    - name: Download Flutter SDK artifacts (flutter precache)
      run: flutter precache --universal
    - name: Download our dependencies (flutter pub get)
      run: flutter pub get
    - name: Use Credentials
      run: |
        echo "${signingKeyPath}" > android/release-keystore.properties
        echo "${signingKey}" | base64 --decode > android/release.keystore
        sed -i "s/APPID/${fcmAppId}/g" lib/firebase_options.dart
        sed -i "s/SENDERID/${fcmSender}/g" lib/firebase_options.dart
        sed -i "s/APIKEY/${fcmApiKey}/g" lib/firebase_options.dart
      env:
          signingKeyPath: ${{ secrets.JKS_KEYPATH }}
          signingKey: ${{ secrets.JKS_KEYSTORE }}
          fcmSender: ${{ secrets.FCM_SENDER }}
          fcmAppId: ${{ secrets.FCM_APP_ID }}
          fcmApiKey: ${{ secrets.FCM_API_KEY }}
    - name: Build APK
      run: flutter build apk --release
    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: zulip-flutter-release-v${{ github.run_number }}.apk
        path: build/app/outputs/flutter-apk/app-release.apk
  mac:
    runs-on: macos-15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Clone Flutter SDK (full)
        run: |
          git clone https://github.com/flutter/flutter.git ~/flutter
          echo ~/flutter/bin >> "$GITHUB_PATH"
          # Flutter expects origin/master to exist, even on main branch
          git --git-dir ~/flutter/.git update-ref refs/remotes/origin/master origin/main
      - name: Download Flutter SDK artifacts (flutter precache)
        run: flutter precache --universal
      - name: Download our dependencies (flutter pub get)
        run: flutter pub get
      - name: Build IPA
        run: flutter build ipa --no-codesign